sudo: required

services:
  - docker

before_install:
  - mkdir -p output
  - mkdir -p output/de
  - mkdir -p output/fr
  - mkdir -p output/es
  - mkdir -p output/pt
  - cp -R docs/images docs/de/
  - cp -R docs/images docs/fr/
  - cp -R docs/images docs/es/
  - cp -R docs/images docs/pt/
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull asciidoctor/docker-asciidoctor:1.17.1

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor:1.17.1 asciidoctor -b html5 -d book -a icons=font -a toc=left -D /documents/output docs/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor:1.17.1 asciidoctor-pdf -D /documents/output docs/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html-de asciidoctor/docker-asciidoctor:1.17.1 asciidoctor -b html5 -d book -a icons=font -a toc=left -D /documents/output/de docs/de/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf-de asciidoctor/docker-asciidoctor:1.17.1 asciidoctor-pdf -D /documents/output/de docs/de/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html-fr asciidoctor/docker-asciidoctor:1.17.1 asciidoctor -b html5 -d book -a icons=font -a toc=left -D /documents/output/fr docs/fr/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf-fr asciidoctor/docker-asciidoctor:1.17.1 asciidoctor-pdf -D /documents/output/fr docs/fr/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html-es asciidoctor/docker-asciidoctor:1.17.1 asciidoctor -b html5 -d book -a icons=font -a toc=left -D /documents/output/es docs/es/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf-es asciidoctor/docker-asciidoctor:1.17.1 asciidoctor-pdf -D /documents/output/es docs/es/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html-pt asciidoctor/docker-asciidoctor:1.17.1 asciidoctor -b html5 -d book -a icons=font -a toc=left -D /documents/output/pt docs/pt/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf-pt asciidoctor/docker-asciidoctor:1.17.1 asciidoctor-pdf -D /documents/output/pt docs/pt/*.adoc

after_error:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_success:
  - cd output ; cp -R ../docs/images images; cp -R ../docs/cockpit-ui cockpit-ui
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

